const ROMANTIC_ACTIVITIES = [
  "Restaurant",
  "Beach",
  "Hotel",
  "Observatory",
  "Sushi Bar",
  "Spa",
  "Hot Air Balloon Launch Site",
  "Cinema",
  "Wine Cellar",
  "Massage Parlor",
  "Park",
  "Dance Studio",
  "Jazz Club",
  "Ski Resort",
  "Planetarium",
  "Art Studio",
  "Boat Dock",
  "Poetry Cafe",
  "Horse Ranch",
  "Art Gallery",
  "Puzzle Room",
  "Concert Hall",
  "Hiking Trail",
  "Theater",
  "Botanical Garden",
  "Drive-In Theater",
  "Luxury Resort",
  "Dessert Cafe",
  "Amusement Park",
  "Dive Shop",
  "Sunrise Spot",
  "Museum",
  "Cooking School",
  "Yoga Studio",
  "Flea Market",
  "Extreme Sports Center",
  "Sports Arena",
  "Fairground",
  "Photo Studio",
  "Pottery Workshop",
  "Casino",
  "Island",
  "Scuba Shop",
  "Music Lounge",
  "Harbor",
  "Golf Course",
  "Balloon Festival",
  "Castle",
];

const PARTY_ACTIVITIES = [
  "Brewery",
  "Karaoke Bar",
  "Grill House",
  "Dance Club",
  "Halloween Store",
  "Cocktail Lounge",
  "Game Cafe",
  "Pub",
  "Event Space",
  "Foosball Bar",
  "Beach Club",
  "Comedy Club",
  "Billiards Hall",
  "Nightclub",
  "Circus",
  "Card Shop",
  "Wine Store",
  "Taco Stand",
  "Photo Studio",
  "Arcade",
  "Lounge",
  "Music Venue",
  "Outdoor Theater",
  "Bakery",
  "Pajama Store",
  "Glow-in-the-Dark Mini Golf",
  "Craft Store",
  "Magic Shop",
  "Trampoline Park",
  "Bingo Hall",
  "Sports Bar",
  "Cafe",
  "Doughnut Shop",
  "Petting Zoo",
  "Casino",
  "Tea House",
  "Pizza Parlor",
  "Disco",
  "Pet Store",
  "Bookstore",
  "Juice Bar",
  "Origami Store",
  "Fishing Spot",
  "Firework Stand",
  "Escape Room",
];

const CULTURAL_ACTIVITIES = [
  "Museum",
  "Theater",
  "Historic Site",
  "Cultural Center",
  "Ethnic Restaurant",
  "Temple",
  "Dance Hall",
  "Art Studio",
  "Cinema",
  "Library",
  "Marketplace",
  "Calligraphy Center",
  "Concert Hall",
  "Art Walk",
  "Lecture Hall",
  "Archaeological Site",
  "Storytelling Center",
  "Craftsmen Workshop",
  "Food Fair",
  "Folk Festival",
  "Language School",
  "Chapel",
  "Board Games Cafe",
  "Photo Exhibit",
  "Astronomy Center",
  "Architectural Tour Spot",
  "Painting Gallery",
  "Cathedral",
  "Improv Workshop",
  "Fashion Boutique",
  "Vintage Cinema",
  "Poetry Club",
  "Orchestra Venue",
  "Castle",
  "Ghost Tour Start",
  "Scriptorium",
  "Science Fair",
  "Opera House",
  "Puppet Theater",
];

const RELAXATION_ACTIVITIES = [
  "Spa",
  "Meditation Center",
  "Bookstore",
  "Beach",
  "Nature Reserve",
  "Bathtub Store",
  "Stationery Store",
  "Teashop",
  "Fishing Pier",
  "Yoga Studio",
  "Bed Shop",
  "Observatory",
  "Garden Center",
  "Knitting Store",
  "Mantra Center",
  "Bird Sanctuary",
  "Beauty Salon",
  "Mountain",
  "Zen Garden",
  "Aromatherapy Store",
  "Art Therapy Center",
  "Writing Workshop",
  "Plant Nursery",
  "Sound Bath Center",
  "Music Store",
  "Pilates Studio",
  "Art Supply Store",
  "Kayak Rental",
  "Gentleman’s Lounge",
  "Forest Reserve",
  "Retreat Center",
  "Ceramic Workshop",
  "Breathing Class",
  "Puzzle Store",
  "Stargazing Point",
  "Hot Springs",
  "Fruit Orchard",
  "Farm",
  "Tai Chi Park",
  "Candle Store",
  "Mirror Shop",
  "Acupuncture Center",
  "Coloring Book Store",
  "Hypnotherapy Center",
  "Boutique",
  "Cat Cafe",
  "Mindfulness Institute",
];

module.exports = {
  ROMANTIC_ACTIVITIES,
  PARTY_ACTIVITIES,
  CULTURAL_ACTIVITIES,
  RELAXATION_ACTIVITIES,
};
